### PR TITLE
fix: Race condition in attacher looking for pod

### LINKED ISSUE #84: bug - attach doesn't always work with `kubectl trace run`
This is (I think) fairly easy to reproduce. If you specify the `-a` flag to `kubectl trace run`, it will often not attach to the trace, and you must manually execute `kubectl trace attach`.

For my case, It actually rarely happens that attach actually does work.

I wonder if it just needs to poll / retry more often or something, or if it can get a better signal about when it should be able to successfully attach.

### PR DESCRIPTION
**Pull request by zqureshi**
Fixes #84 

When you do `kubectl trace run --attach` the job will have been created by `TraceJobClient` but the pod is not guaranteed to have been scheduled on any node. Therefore we cannot error out if no pod is found and must continue retrying.

It is easy to reproduce if you put a `panic()` in that area and I seem to hit it about 20% of my runs.

I also made it so that all errors encountered by the attacher are logged because they were silent right now and you wouldn't know that you attached to a blank `bpftrace` screen or attach failed and the local process is just waiting for a Ctrl-C.

@dalehamel @fntlnz

### CODE REVIEW

File: pkg/attacher/attach.go [hunk 1]
```diff
@@ -52,55 +52,63 @@ func (a *Attacher) AttachJob(traceJobID types.UID, namespace string) {
...
-		err = t.Safe(ao.defaultAttachFunc())
-
-		if err != nil {
-			// on error, just send false so that the backoff mechanism can do a new tentative
-			return false, nil
-		}
-		return true, nil
-	})
+	}()
 	<-a.ctx.Done()
```
Comment (zqureshi) [inline pkg/attacher/attach.go:112]: I think it would also be nice to have some sort of messaging here that tells the user that they have been detached and is waiting.

**Review by fntlnz — APPROVED** [review]
LGTM!
